[server]
maxUploadSize = 100

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#E4572E"
backgroundColor = "#FCFDFB"
secondaryBackgroundColor = "#F3F6F3"
textColor = "#18221C"
font = "sans serif"
